### PR TITLE
cmd_vel to 0 when deadman button is released

### PR DESCRIPTION
**Pull request by martimorta**
Hi,
I am not sure if this was the right behaviour but using the node in simulation I've found out that the robot kept following the last velocity command after deadman button was released.
To fix that I published a zero twist when deadman_pressed_ is false.
Cheers.

### CODE REVIEW

**Comment by jihoonl** [comment]
@martimorta   Thanks for the patch. 

Can you explain how exactly robot mishaves? The robot moves even if deadman button is released? If you can attach any video, it would be awesome to understand the bug.

**Comment by martimorta** [comment]
_Misbehaviour_
Press LB (deadman button) + Move L stick = Robot moves
Hold L stick in moving position + Release LB = Robot still moving with the last command
[video](https://plus.google.com/photos/+Mart%C3%ADMorta/albums/5971290709625591345/5971286091772699058?authkey=CNTnvqH1pea6Ug&pid=5971286091772699058&oid=107939324664655967944)

_Fix_
Press LB (deadman button) + Move L stick = Robot moves
Hold L stick in moving position + Release LB = Robot stops
[video](https://plus.google.com/photos/+Mart%C3%ADMorta/albums/5971290709625591345/5971285988530409634?authkey=CNTnvqH1pea6Ug&pid=5971285988530409634&oid=107939324664655967944)

**Comment by bit-pirate** [comment]
Thanks for your contribution @martimorta, however I think this patch is taking the wrong approach.
For TB we implemented timeouts for velocity commands, i.e. the robot stops moving after a certain time has passed since the last received command. There are also tools, such as the velocity muxer (https://github.com/yujinrobot/yujin_ocs/tree/hydro/yocs_cmd_vel_mux), which builds on top of that assumption.

To solve your problem, I suggest you implement a similar timeout in the Gazebo plugin for your robot simulation.

**Comment by martimorta** [comment]
Thanks I will have a look
I think that would be a good idea to clarify this approach in the turtlebot_teleop package since the deadman button doesn't work as one would expect.
In my application I only need an xbox controller so my patch will do :)
Sorry for any inconveniences!

**Comment by chadrockey** [comment]
@jihoonl @martimorta @bit-pirate 

I noticed this the other day.  Personally, I agree with @martimorta that the deadman switch should cause the robot to stop as soon as possible.  Typically deadman switches are hair-triggers that do something immediately after the trigger condition.  In movies, it's used to destroy the planet if anyone causes the bad guy's hand to slip.  In robots, and the original source for this teleop, it's use to send zero velocities.

https://github.com/bosch-ros-pkg/pr2_apps/blob/master/pr2_teleop/src/teleop_pr2.cpp#L363

Of course, the PR2 uses the old style service call mux.  So it's easy to not plaster your vehicle with zero commands.  Turtlebot uses a newer style mux based on rates, so @martimorta 's solution will clobber navigation and following if teleop is also enabled.

I'm not familiar enough with turtlebot's cmd_vel mux, but I would recommend that the deadman send zeros for at least  a second or two after release.  Here is the situation that I think justifies sending zeros:

Two turtlebots are loaded and ready to be driven.  Two operators (Operator A - experienced and Operator B - new on the job) drive the turtlebots with the teleop node on a ps3 controller.  Everything goes well until they reach a crosswalk at a busy intersection.  When the walk sign turns on, they begin across the street - but a truck runs the light!  Operator A is well trained and releases the joystick, BUT NOT the deadman button, this causes zero velocities to be commanded to his turtlebot which immediately stops.  Operator B panics and drops the controller!  Their turtlebot is now moving while not being commanded!  It will continue drifting on the last command until the hardware timeout eventually activates and stops the robot.  However, it's too late for Turtlebot B, as the 20cms brings it right under the truck tires.  RIP turtlebot.

---

Anyway, besides the flowery description, this was WAY more important on the PR2 than the Turtlebot.  If the PR2 went forward for 0.2 to 0.4 seconds (20 to 40 cm) uncontrolled, glass, cars, feet, and PR2s would all be seriously injured.  Turtlebot isn't as safety critical, but as it is currently the ROS reference robot, we can save a lot of researchers' feet and walls if we can implement this as a true deadman switch.

**Comment by bit-pirate** [comment]
Thanks a lot, Chad! Your elaboration on this issue made my morning! :smile: 

What about this:
Let's send out **one** zero twist message, when the deadman button is released. That should make the robot stop and would not mess with the velocity muxer. I would also recommend to make the publisher latched.

**Comment by martimorta** [comment]
I made the changes @bit-pirate suggested and tested them in gazebo and everything works fine, using our robot and turtlebot with velocity muxer.

btw, @chadrockey I am your fan! Amusing description :)

**Comment by jihoonl** [comment]
The pull request just have tested and confirm that it works well. Sorry for late merging. couldn't get a joystick until now.

**Comment by bit-pirate** [comment]
Please also cherry-pick over to hydro-devel.

**Pull request merged**
