### PR TITLE
This removes the pcl dependency and changes the follower to use the depth image instead of the point cloud

### PR DESCRIPTION
**Pull request by tfoote**
This has the added benefit of not requiring PCL as a dependency.

Available for review but I'll test this in the office tomorrow before merging.

### CODE REVIEW

**Comment by tfoote** [comment]
I validated this today and fixed up a few indexing errors. It decreases the cpu load from 4 saturated cores to 1 saturated core.

**Comment by 130s** [comment]
@tfoote Out of curiosity, what's the background of this PR?
Is there any other reason than fewer dependency the better as a general rule of thumb?

**Comment by tfoote** [comment]
Fewer dependencies make releasing easier and less footprint. Lower computational overhead allows cheaper processors and longer battery life.

**Comment by stonier** [comment]
This particular application is easily suited to iterating over the 2d image. The 3d point clouds just seem like massive overkill in retrospect.  So +1 from me especially as it is probably the most popular reference application for turtles (no preparation needed like navigation requires).

**Pull request merged**
