### PR TITLE
Safer behavior for Turtlebot Follower

### PR DESCRIPTION
**Pull request by chadrockey**
This commit prevents the turtlebot from running over feet/up legs in order to reach the center of the centroid along the z-axis.

Previously, if you stood with your legs apart, someone standing behind you, or with a wall behind you, the centroid would be past your legs/feet.

Using the closest z-reading instead of the centroid is much safer for people with open-toed shoes.  This also has the benefit of being able to free the turtlebot from walls and obstacles simply by stepping in front of the turtlebot.

### CODE REVIEW

**Comment by tfoote** [comment]
+1

**Comment by bit-pirate** [comment]
I like this!

**Comment by stonier** [comment]
Looks good. I'll get a new deb rolling this afternoon.

**Pull request merged**
