### PR TITLE
[WIP] Integrate frontier_exploration.

### PR DESCRIPTION
**Pull request by 130s**
**Do not review yet, but opinion needed.**

Adding a launch and a param file for [frontier_exploration](http://wiki.ros.org/frontier_exploration). 

**Question**. Particularly because I'm adding dependency, I thought I would add this as a separate package (e.g. turtlebot_samples). However, I'm not adding a sample, instead I'm adding a feature that user's application can utilize, thus I'm adding as another feature in `turtlebot_navigation`. Is this okay approach?

### CODE REVIEW

**Comment by trainman419** [comment]
The turtlebot stack already has a significant number of dependencies that slow down the release process.

Instead of adding yet another dependency and increase the load on the maintainers, it's probably better to release these launch files as a new package.

**Comment by 130s** [comment]
Still not ready for the review, but I just created `turtlebot_apps/turtlebot_samples` package to put all the proposed files in. As you see it's still in `turtlebot_apps` metapkg. Is this what you meant? @trainman419 Or do we want to create a whole new repository?

**Comment by trainman419** [comment]
Having this in the same repository still makes the release of turtlebot_apps depend on the frontier_exploration package and doesn't address any of the issues raised in my previous comment.

**Comment by 130s** [comment]
Can any admins of `turtlebot` organization create a repository for `turtlebot_samples` (or whatever  makes the best sense)?

**Comment by trainman419** [comment]
You can create the package on your own account, demonstrate its viability and usefulness, and then petition to get it moved into the turtlebot organization. You don't need to bother the package maintainers for your personal project.

**Pull request closed without merging**
