### PR TITLE
This makes turtlebot_calibration work again

### PR DESCRIPTION
**Pull request by mikeferguson**

### CODE REVIEW

**Comment by stonier** [comment]
@jorge can you quickly re-release turtlebot_apps? I think a few people were waiting on this one.

**Comment by mikeferguson** [comment]
Also, just a heads up, this went into master branch, I notice you have a groovy branch as well, so you will want to pull it in there before a release if that is where you are releasing from.

**Comment by stonier** [comment]
Groovy is just the automatically created branch by ros-release. We'll change branch behaviours when we catkinize.

**Comment by mikeferguson** [comment]
Ah ok. I haven't released any non-catkinized stacks out of git before....

**Pull request merged**
